import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, Search, Send, X } from 'lucide-react';
import type { ChatContact } from '../components/explore/PersonDetailCard';
import { chats, people } from '../data/demoData';
import { backendCurrentUserId, ensureDirectConversation, loadBackendChats, loadBackendMessages, sendBackendMessage, type BackendChatMessage, type BackendChatPreview } from '../lib/chatBackend';
import { blockedNames, loadBlockedUsers } from '../lib/privacy';
import { supabase } from '../lib/supabase';
import { loadStored, saveStored, storageChangeEvent, storageKeys } from '../lib/storage';
import type { ChatItem, ChatTab } from '../types';
const groupNames=new Set(['Grupo Pádel','Viaje a Madrid','Running Tarragona','Cine y palomitas']);
const fallbackAvatars=['./assets/images/photo-1500648767791-00dcc994a43e.jpg','./assets/images/photo-1494790108377-be9c29b29330.jpg','./assets/images/photo-1507003211169-0a1dd7228f2d.jpg','./assets/images/photo-1534528741775-53994a69daeb.jpg','./assets/images/photo-1507591064344-4c6ce005b128.jpg','./assets/images/photo-1544005313-94ddf0286df2.jpg'];
const avatarFor=(name:string,index=0)=>people.find(person=>person.name===name)?.image||fallbackAvatars[index%fallbackAvatars.length];const chatKey=(item:ChatItem)=>item.conversationId||`demo:${item.name}:${item.isGroup?'group':'direct'}`;const planTargetId=(target:string|null|undefined)=>target?.startsWith('plan:')?target.slice(5):null;
export function ChatView({initialContact=null,initialPlanTarget=null}:{initialContact?:ChatContact|null;initialPlanTarget?:string|null}){
 const [blocked,setBlocked]=useState<Set<string>>(()=>blockedNames());const [blockedIds,setBlockedIds]=useState<Set<string>>(()=>new Set(loadBlockedUsers().map(user=>user.userId)));const [tab,setTab]=useState<ChatTab>('Todos');const [searchOpen,setSearchOpen]=useState(false);const [query,setQuery]=useState('');const [activeChat,setActiveChat]=useState<string|null>(()=>initialPlanTarget||(initialContact&&!blocked.has(initialContact.name)?initialContact.name:null));const [drafts,setDrafts]=useState<Record<string,string>>({});const [sent,setSent]=useState<Record<string,string[]>>(()=>loadStored(storageKeys.chatMessages,{}));const [backendChats,setBackendChats]=useState<BackendChatPreview[]>([]);const [backendThreads,setBackendThreads]=useState<Record<string,BackendChatMessage[]>>({});const [backendUserId,setBackendUserId]=useState<string|null>(null);const [backendLoaded,setBackendLoaded]=useState(false);const [sendingByChat,setSendingByChat]=useState<Record<string,boolean>>({});const [errorsByChat,setErrorsByChat]=useState<Record<string,string>>({});const [threadError,setThreadError]=useState('');
 const draftKey=activeChat||'';const draft=drafts[draftKey]||'';const sending=Boolean(sendingByChat[draftKey]);const sendError=errorsByChat[draftKey]||'';
 const setDraft=(value:string)=>setDrafts(current=>({...current,[draftKey]:value}));
 const setSending=(value:boolean)=>setSendingByChat(current=>({...current,[draftKey]:value}));
 const setSendError=(value:string)=>setErrorsByChat(current=>({...current,[draftKey]:value}));
 useEffect(()=>{saveStored(storageKeys.chatMessages,sent)},[sent]);
 useEffect(()=>{const refreshBlocked=()=>{setBlocked(blockedNames());setBlockedIds(new Set(loadBlockedUsers().map(user=>user.userId)));};const onStorageChange=(event:Event)=>{const detail=(event as CustomEvent<{key?:string}>).detail;if(detail?.key===storageKeys.blockedUsers)refreshBlocked();};window.addEventListener(storageChangeEvent,onStorageChange);window.addEventListener('storage',refreshBlocked);return()=>{window.removeEventListener(storageChangeEvent,onStorageChange);window.removeEventListener('storage',refreshBlocked);};},[]);
 useEffect(()=>{let active=true;setBackendLoaded(false);void Promise.all([loadBackendChats(),backendCurrentUserId()]).then(([realChats,userId])=>{if(!active)return;setBackendChats(realChats);setBackendUserId(userId);}).catch(error=>console.warn('CONECTA real chat unavailable; demo fallback kept',error)).finally(()=>{if(active)setBackendLoaded(true)});return()=>{active=false};},[]);
 useEffect(()=>{if(initialPlanTarget){setActiveChat(initialPlanTarget);return;}if(!initialContact)return;if(blocked.has(initialContact.name)||(initialContact.userId&&blockedIds.has(initialContact.userId)))return;if(!initialContact.userId){setActiveChat(initialContact.name);return;}let active=true;setBackendLoaded(false);void ensureDirectConversation(initialContact.userId).then(async conversationId=>{const realChats=await loadBackendChats();if(!active)return;setBackendChats(realChats);setActiveChat(conversationId);}).catch(error=>{console.warn('CONECTA direct conversation unavailable',error);if(active)setThreadError(error instanceof Error?error.message:'No se ha podido abrir la conversación.');}).finally(()=>{if(active)setBackendLoaded(true)});return()=>{active=false};},[initialContact?.name,initialContact?.userId,initialPlanTarget,blocked,blockedIds]);
 const items=useMemo<ChatItem[]>(()=>{const realItems:ChatItem[]=backendChats.filter(real=>real.userId?!blockedIds.has(real.userId):(real.isGroup||!blocked.has(real.name))).map((real,index)=>({name:real.name,msg:real.message,count:'',isGroup:real.isGroup,avatar:real.avatar||avatarFor(real.name,index),conversationId:real.conversationId,userId:real.userId,planId:real.planId}));const realNames=new Set(realItems.map(item=>item.name.trim().toLocaleLowerCase('es')));const demoItems:ChatItem[]=chats.map(([name,msg,count],i)=>({name,msg,count,isGroup:groupNames.has(name),avatar:avatarFor(name,i)})).filter(item=>(item.isGroup||!blocked.has(item.name))&&!realNames.has(item.name.trim().toLocaleLowerCase('es')));const base=[...realItems,...demoItems];if(initialContact&&!initialContact.userId&&!blocked.has(initialContact.name)&&!base.some(item=>item.name===initialContact.name))base.unshift({name:initialContact.name,msg:'Nueva conversación',count:'',isGroup:false,avatar:avatarFor(initialContact.name)});return base;},[initialContact?.name,initialContact?.userId,blocked,blockedIds,backendChats]);
 const activeItem=useMemo(()=>activeChat?items.find(item=>chatKey(item)===activeChat||item.name===activeChat||(item.planId&&`plan:${item.planId}`===activeChat)):undefined,[activeChat,items]);
 useEffect(()=>{setSendError('');const conversationId=activeItem?.conversationId;if(!conversationId)return;let active=true;let loading=false;const refresh=async()=>{if(loading)return;loading=true;await loadBackendMessages(conversationId).then(messages=>{if(active){setBackendThreads(current=>({...current,[conversationId]:messages}));setThreadError('');}}).catch(error=>{console.warn('CONECTA real thread unavailable; demo fallback kept',error);if(active)setThreadError('No se han podido cargar los mensajes sincronizados. Puedes volver atrás e intentarlo de nuevo.');});loading=false;};void refresh();const channel=supabase.channel(`chat:${conversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},()=>{void refresh()}).subscribe();const interval=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh()},30000);window.addEventListener('focus',refresh);return()=>{active=false;window.clearInterval(interval);window.removeEventListener('focus',refresh);void supabase.removeChannel(channel);};},[activeItem?.conversationId]);
 const visible=useMemo(()=>items.filter(item=>{if(tab==='Grupos'){if(!item.isGroup)return false;if(item.conversationId&&item.planId)return false;}if(tab==='Planes'){if(item.conversationId&&!item.planId)return false;if(!item.conversationId&&item.isGroup)return false;}const q=query.trim().toLocaleLowerCase('es');return !q||`${item.name} ${item.msg}`.toLocaleLowerCase('es').includes(q);}),[items,tab,query]);
 if(activeChat){const item=activeItem;if(!item&&!backendLoaded)return <div className="page chat-page"><div className="empty-state"><strong>Cargando conversación…</strong><span>Conectando con el chat sincronizado.</span></div></div>;if(!item)return <div className="page chat-page"><div className="empty-state"><strong>Esta conversación ya no está disponible.</strong><span>{threadError||'Puede haberse cerrado o haber cambiado tu acceso.'}</span><button type="button" onClick={()=>setActiveChat(null)}>Volver a chats</button></div></div>;const localMessages=item.conversationId?[]:(sent[item.name]||[]);const realMessages=item.conversationId?backendThreads[item.conversationId]||[]:[];const send=async()=>{const text=draft.trim();if(!text||sending)return;setDraft('');setSendError('');setSending(true);let delivered=false;try{if(item.conversationId){const sentReal=await sendBackendMessage(item.conversationId,text);if(!sentReal)throw new Error('La conversación no está disponible para envío.');delivered=true;const refreshed=await loadBackendMessages(item.conversationId);setBackendThreads(current=>({...current,[item.conversationId as string]:refreshed}));setBackendChats(await loadBackendChats());}else setSent(value=>({...value,[item.name]:[...(value[item.name]||[]),text]}));}catch(error){console.warn('CONECTA real message send failed; message not marked as sent',error);if(!delivered)setDraft(text);setSendError(delivered?'Mensaje enviado. No se ha podido actualizar la conversación; se volverá a consultar automáticamente.':error instanceof Error?error.message:'No se ha podido enviar el mensaje. Comprueba tu conexión e inténtalo otra vez.');}finally{setSending(false);}};return <div className="page chat-page"><div className="chat-thread-head"><button type="button" aria-label="Volver a chats" onClick={()=>setActiveChat(null)}><ChevronLeft/></button><img src={item.avatar} alt={item.name}/><div><strong>{item.name}</strong><span>Conversación</span></div></div><div className="chat-thread">{realMessages.length?realMessages.map(message=><div className={`message ${message.senderId===backendUserId?'sent':'received'}`} key={message.id}>{message.content}</div>):<div className="message received">{item.msg}</div>}{localMessages.map((message,index)=><div className="message sent" key={`${message}-${index}`}>{message}</div>)}</div>{threadError&&<div className="auth-message" role="status">{threadError}</div>}{sendError&&<div className="auth-message" role="alert">{sendError}</div>}<div className="chat-composer"><input value={draft} disabled={sending} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.nativeEvent.isComposing){event.preventDefault();void send();}}} placeholder="Escribe un mensaje..." aria-label="Escribe un mensaje"/><button type="button" disabled={sending||!draft.trim()} onClick={()=>{void send();}} aria-label="Enviar mensaje"><Send/></button></div></div>;}
 const blockedAttempt=Boolean(initialContact&&(blocked.has(initialContact.name)||(initialContact.userId&&blockedIds.has(initialContact.userId))));return <div className="page chat-page"><div className="page-title"><div><h1>Chat</h1><p>Tus conversaciones y grupos</p></div><button type="button" aria-label="Buscar conversaciones" onClick={()=>setSearchOpen(value=>!value)}>{searchOpen?<X/>:<Search/>}</button></div>{blockedAttempt&&<div className="empty-state">Este usuario está bloqueado. Puedes gestionarlo desde Ajustes → Privacidad → Usuarios bloqueados.</div>}{threadError&&<div className="auth-message" role="alert">{threadError}</div>}{searchOpen&&<div className="explore-search"><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar conversación" aria-label="Buscar conversación"/></div>}<div className="tabs">{(['Todos','Planes','Grupos'] as ChatTab[]).map(item=><button type="button" key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="chat-list">{visible.length?visible.map(item=><button type="button" key={chatKey(item)} onClick={()=>setActiveChat(chatKey(item))}><img loading="lazy" decoding="async" src={item.avatar} alt={item.name}/><div><strong>{item.name}</strong><span>{item.conversationId?item.msg:(sent[item.name]?.at(-1)||item.msg)}</span></div>{item.count&&<b>{item.count}</b>}</button>):<div className="empty-state"><strong>{query.trim()?'No encontramos conversaciones':tab==='Planes'?'Aún no tienes chats de planes':tab==='Grupos'?'Aún no tienes grupos activos':'Aún no tienes conversaciones'}</strong><span>{query.trim()?'Prueba con otro nombre o mensaje.':'Cuando conectes con personas o planes, aparecerán aquí.'}</span></div>}</div></div>;
}
