import { useEffect, useState } from 'react';
import { CalendarDays, ChevronLeft, Heart, MapPin, Map, Users } from 'lucide-react';
import { CategoryIcon } from '../components/CategoryIcon';
import { PlanCards } from '../components/PlanComponents';
import { categories, escapes, people, plans } from '../data/demoData';
import { filterExplorePlans, planIdentityKey } from '../lib/planLogic';
import { loadStored, saveStored, storageKeys } from '../lib/storage';
import type { ExploreFilter, HomeBrowseMode, Plan } from '../types';

const modeTitle:Record<HomeBrowseMode,string>={all:'Explorar planes',categories:'Categorías',near:'Planes cerca de ti',today:'Planes de hoy',afternoon:'Esta tarde',tonight:'Esta noche',weekend:'Este finde',escapes:'Escapadas y eventos',people:'Personas compatibles'};
function plansFor(mode:HomeBrowseMode,category:string|null):Plan[]{if(category)return plans.filter(plan=>plan.category===category);if(mode==='near')return plans.slice(0,6);if(mode==='today')return plans.filter(plan=>plan.time.startsWith('Hoy'));if(mode==='afternoon')return plans.filter(plan=>/17:|18:|19:/.test(plan.time));if(mode==='tonight')return plans.filter(plan=>/20:|21:|22:/.test(plan.time));if(mode==='weekend')return plans.filter(plan=>/Sáb|Dom|Vie/.test(plan.time));return plans;}
function cleanMatch(value:string){const parsed=Number.parseInt(value.replace(/[^0-9]/g,''),10);return Number.isNaN(parsed)?value:`${Math.min(100,Math.max(0,parsed))}%`;}

export function HomeBrowseView({mode,category,onBack,onPlan,onBrowse,extraPlans=[]}:{mode:HomeBrowseMode;category:string|null;extraPlans?:Plan[];onBack:()=>void;onPlan:(plan:Plan)=>void;onBrowse:(mode:HomeBrowseMode,category?:string|null)=>void;}){
  const title=category?category:modeTitle[mode];
  const realFilter:ExploreFilter=['near','today','afternoon','tonight','weekend'].includes(mode)?mode as ExploreFilter:'all';
  const realPlans=filterExplorePlans(extraPlans,{timeFilter:realFilter,category,query:'',sortAsc:true});
  const visiblePlans=[...realPlans,...plansFor(mode,category)];
  const [favorites,setFavorites]=useState<string[]>(()=>loadStored(storageKeys.planFavorites,[]));
  const toggleFavorite=(plan:Plan)=>{const key=planIdentityKey(plan);const next=favorites.includes(key)?favorites.filter(item=>item!==key):[...favorites,key];setFavorites(next);saveStored(storageKeys.planFavorites,next);};
  useEffect(()=>{window.scrollTo({top:0,behavior:'auto'});},[mode,category]);
  return <div className="page home-browse-page home-browse-premium"><span className="home-browse-blob home-browse-blob-a"/><span className="home-browse-blob home-browse-blob-b"/>
    <header className="home-browse-header"><div className="home-browse-heading"><small>CONECTA</small><h1>{title}</h1><p>Descubre, participa y vive más</p></div><button className="home-browse-back" type="button" aria-label="Volver a Inicio" onClick={onBack}><ChevronLeft/></button></header>
    {(mode==='near'||mode==='all'||mode==='today'||mode==='weekend')&&!category&&<nav className="home-browse-time-row" aria-label="Cuándo quieres hacer un plan"><button className={mode==='near'||mode==='all'?'active':''} type="button" onClick={()=>onBrowse('near',null)}><MapPin/>Cerca de ti</button><button className={mode==='today'?'active':''} type="button" onClick={()=>onBrowse('today',null)}><CalendarDays/>Hoy</button><button className={mode==='weekend'?'active':''} type="button" onClick={()=>onBrowse('weekend',null)}><CalendarDays/>Este fin de semana</button><button type="button" onClick={()=>onBrowse('near',null)}><Map/>Mapa</button></nav>}
    {mode==='categories'&&!category&&<section className="home-browse-grid home-browse-categories" aria-label="Categorías">{categories.map(([name,image])=><button type="button" key={name} onClick={()=>onBrowse('categories',name)}><img loading="lazy" decoding="async" src={image} alt=""/><span className="home-browse-category-label"><CategoryIcon name={name}/>{name}</span><b>›</b></button>)}</section>}
    {mode==='escapes'&&<section className="home-browse-grid home-browse-escapes" aria-label="Escapadas y eventos">{escapes.map(([name,date,image])=><article key={name} role="button" tabIndex={0} onClick={()=>onPlan({title:name,image,time:date,place:name,distance:'',spots:'8 plazas',category:'Viajes'})} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onPlan({title:name,image,time:date,place:name,distance:'',spots:'8 plazas',category:'Viajes'})}}}><img loading="lazy" decoding="async" src={image} alt=""/><div><strong>{name}</strong><span><MapPin/>{date}</span></div></article>)}</section>}
    {mode==='people'&&<section className="home-browse-grid home-browse-people" aria-label="Personas compatibles">{people.map(person=><article className="home-browse-person" key={person.name}><div className="home-browse-person-photo"><img loading="lazy" decoding="async" src={person.image} alt={`Foto de ${person.name}`}/><span>{cleanMatch(person.match)} compatible</span></div><div className="home-browse-person-body"><div className="home-browse-person-main"><strong>{person.name}, {person.age}</strong><span>{person.distance}</span></div><div className="home-browse-person-tags">{person.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><p>{person.bio}</p></div></article>)}</section>}
    {mode!=='categories'&&mode!=='escapes'&&mode!=='people'&&<section className="home-browse-plan-grid" aria-label={title}>{visiblePlans.map((plan,index)=><article className="home-browse-plan-card" key={planIdentityKey(plan)} role="button" tabIndex={0} onClick={()=>onPlan(plan)} onKeyDown={event=>{if(event.target!==event.currentTarget)return;if(event.key==='Enter'||event.key===' '){event.preventDefault();onPlan(plan)}}}><div className="home-browse-plan-image"><img loading="lazy" decoding="async" src={plan.image} alt={plan.title}/><span className="home-browse-date-badge">{plan.time.split('·')[0].trim()}</span></div><div className="home-browse-plan-body"><div className="home-browse-plan-title"><strong>{plan.title}</strong><button type="button" aria-label={`Guardar ${plan.title}`} aria-pressed={favorites.includes(planIdentityKey(plan))} onClick={event=>{event.stopPropagation();toggleFavorite(plan)}}><Heart fill={favorites.includes(planIdentityKey(plan))?'currentColor':'none'}/></button></div><span><CalendarDays/>{plan.time}</span><span><MapPin/>{plan.place}{plan.distance?` · ${plan.distance}`:''}</span><span><Users/>{plan.spots}</span><div className="home-browse-plan-footer"><div className="home-browse-plan-avatars">{people.slice(index%3,index%3+3).map(person=><img key={person.name} src={person.image} alt="" loading="lazy" decoding="async"/>)}<b>+{index+2}</b></div><button type="button" className="home-browse-plan-open" onClick={event=>{event.stopPropagation();onPlan(plan)}}>Ver plan <span>→</span></button></div></div></article>)}</section>}
    {mode==='categories'&&category&&<PlanCards items={visiblePlans} onPlan={onPlan}/>} 
  </div>;
}
