import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Coffee, CreditCard, Dumbbell, Heart, MapPin, Music2, Sparkles, Tag } from 'lucide-react';
import { CategoryIcon } from '../components/CategoryIcon';
import { categories, people, plans } from '../data/demoData';
import { blockedNames } from '../lib/privacy';
import { loadSocialSummary, type SocialSummary } from '../lib/socialSummaryBackend';
import type { HomeBrowseMode, Plan } from '../types';

const emptySummary:SocialSummary={attendedThisWeek:0,attendedLast7Days:0,streakWeeks:0,topCategory:null,nextPlan:null,weekPlans:[],upcomingPlans:[]};
const categoryOrder=[
  {label:'Deporte',source:'Deporte'},{label:'Gastronomía',source:'Comida'},{label:'Ocio',source:'Música'},{label:'Viajes',source:'Viajes'},
  {label:'Fitness',source:'Deporte'},{label:'Música/Noche',source:'Música'},{label:'Aire libre',source:'Playa'},{label:'Cultura',source:'Viajes'}
];
function nextPlanDate(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return 'Fecha por confirmar';return new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(date)}

export function HomeView({onPlan,onBrowse}:{onPlan:(p:Plan)=>void,onBrowse:(mode:HomeBrowseMode,category?:string|null)=>void}){
  const [blocked]=useState<Set<string>>(()=>blockedNames());const [summary,setSummary]=useState<SocialSummary>(emptySummary);const [summaryReady,setSummaryReady]=useState(false);
  useEffect(()=>{let active=true;void loadSocialSummary().then(value=>{if(active)setSummary(value)}).catch(error=>console.warn('CONECTA next plan unavailable; demo remains available elsewhere',error)).finally(()=>{if(active)setSummaryReady(true)});return()=>{active=false}},[]);
  const homeCategories=useMemo(()=>categoryOrder.map(item=>{const found=categories.find(([category])=>category===item.source);return {name:item.label,source:item.source,image:found?.[1]||plans[0].image}}),[]);const allowedPeople=useMemo(()=>people.filter(person=>!blocked.has(person.name)),[blocked]);const imageFor=(name:string,fallback:string)=>categories.find(([category])=>category===name)?.[1]||fallback;
  const featuredPlan:Plan|null=summaryReady&&summary.nextPlan?{backendId:summary.nextPlan.id,title:summary.nextPlan.title,image:plans[5]?.image||plans[0].image,time:nextPlanDate(summary.nextPlan.startsAt),startsAt:summary.nextPlan.startsAt,place:summary.nextPlan.location||'Centre de Reus',distance:'',spots:'Plan confirmado',category:summary.nextPlan.category||'Plan'}:null;
  const nearbyPlans:Plan[]=[{title:'Entreno en grupo',image:imageFor('Deporte',plans[0].image),time:'Hoy · 19:00',place:'Vila-seca',distance:'2 km',spots:'+8',category:'Deporte'},{title:'Tapas en el centro',image:imageFor('Comida',plans[1].image),time:'Hoy · 21:00',place:'Tarragona',distance:'4 km',spots:'+5',category:'Comida'},{title:'Atardecer y charlas',image:'./assets/images/photo-1507525428034-b723cf961d3e.jpg',time:'Mañana · 17:00',place:'La Pineda',distance:'7 km',spots:'+12',category:'Playa'}];
  const compatiblePeople=[{name:'Laura',age:26,match:'92%',tags:['Viajes','Café'],image:allowedPeople.find(person=>person.name==='Laura')?.image||people[2].image},{name:'Javi',age:28,match:'88%',tags:['Deporte','Naturaleza'],image:allowedPeople.find(person=>person.name==='Javi')?.image||people[1].image},{name:'Marta',age:24,match:'86%',tags:['Música','Planes'],image:allowedPeople.find(person=>person.name==='Marta')?.image||people[0].image},{name:'Álex',age:27,match:'84%',tags:['Comida','Viajes'],image:allowedPeople.find(person=>person.name==='Álex')?.image||people[5].image}].filter(person=>!blocked.has(person.name));
  const homeEscapes=[{title:'Costa Brava',subtitle:'Escapada de fin de semana',image:'./assets/images/photo-1500530855697-b586d89ba3ee.jpg',place:'Costa Brava'},{title:'Pirineos',subtitle:'Senderismo y naturaleza',image:'./assets/images/photo-1464822759023-fed622ff2c3b.jpg',place:'Pirineos'},{title:'Barcelona',subtitle:'Planes, cultura y más',image:'./assets/images/photo-1539037116277-4db20889f2d4.jpg',place:'Barcelona'}];
  const browse=(mode:HomeBrowseMode,category:string|null=null)=>onBrowse(mode,category);const openEscape=(item:(typeof homeEscapes)[number])=>onPlan({title:item.title,image:item.image,time:'Próximo fin de semana',place:item.place,distance:'',spots:'8 plazas',category:'Viajes'});
  return <div className="page home-page home-target">
    <section className="home-target-hero"><img decoding="async" fetchPriority="high" src="./assets/images/photo-1529156069898-49953e39b3ac.jpg" alt="Grupo de amigos disfrutando de un plan"/><div className="home-target-hero-shade"/><div className="home-target-copy"><h1>Vive más<br/>planes <span>juntos</span></h1><p>Conoce gente, organiza planes<br/>y crea experiencias reales.</p><button type="button" onClick={()=>browse('all')}>Explorar planes <ChevronRight/></button></div><div className="home-target-note">Buenas<br/>compañías<br/>mejores historias</div></section>
    {featuredPlan ? <button className="home-target-next" type="button" onClick={()=>onPlan(featuredPlan)}><img src={featuredPlan.image} alt={featuredPlan.title} decoding="async"/><span className="home-target-next-copy"><small>TU PRÓXIMO PLAN</small><strong>{featuredPlan.title}</strong><span className="home-target-meta"><CalendarDays/>{featuredPlan.time}<i/><MapPin/>{featuredPlan.place}</span><span className="home-target-attendees"><span className="home-target-avatars"><img loading="lazy" decoding="async" src={people[0].image} alt="Participante"/><img loading="lazy" decoding="async" src={people[2].image} alt="Participante"/><img loading="lazy" decoding="async" src={people[1].image} alt="Participante"/><b>+12</b></span><em>{featuredPlan.spots}</em></span></span><span className="home-target-next-arrow"><ChevronRight/></span></button> : summaryReady && <button className="home-target-next" type="button" onClick={()=>browse('all')}><span className="home-target-next-copy"><small>TU PRÓXIMO PLAN</small><strong>Aún no tienes ningún plan confirmado</strong><span className="home-target-meta">Explora planes cerca de ti para apuntarte al primero</span></span><span className="home-target-next-arrow"><ChevronRight/></span></button>}
    <section className="home-target-section"><div className="home-target-head"><h2>Explora por categorías</h2><button onClick={()=>browse('categories')}>Ver todas <ChevronRight/></button></div><div className="home-target-categories">{homeCategories.map(item=><button key={item.name} onClick={()=>browse('categories',item.source)}><img loading="lazy" decoding="async" src={item.image} alt={item.name}/><span/><b><CategoryIcon name={item.source}/>{item.name}</b></button>)}</div></section>
    <section className="home-target-section"><div className="home-target-head"><h2>Descubre planes cerca de ti</h2><button data-testid="nearby-entry" onClick={()=>browse('near')}>Ver todo <ChevronRight/></button></div><div className="home-target-plans">{nearbyPlans.map(plan=><article key={plan.title} role="button" tabIndex={0} onClick={()=>onPlan(plan)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onPlan(plan)}}}><img loading="lazy" decoding="async" src={plan.image} alt={plan.title}/><span className="home-target-card-shade"/><Heart className="home-target-heart"/><div><small>{plan.time}</small><strong>{plan.title}</strong><span><MapPin/>{plan.place}</span><b>{plan.spots}</b></div></article>)}</div></section>
    <section className="home-target-section now-section"><div className="section-head home-target-head"><h2>¿Cuándo quieres salir?</h2><button type="button" onClick={()=>browse('when')}>Ver todo <ChevronRight/></button></div><div className="quick-grid"><button type="button" onClick={()=>browse('today')}><Sparkles/><strong>Ahora mismo</strong><span>Planes de hoy</span></button><button type="button" onClick={()=>browse('afternoon')}><Coffee/><strong>Esta tarde</strong><span>Planes de tarde</span></button><button type="button" onClick={()=>browse('tonight')}><Music2/><strong>Esta noche</strong><span>Planes nocturnos</span></button><button type="button" onClick={()=>browse('weekend')}><CalendarDays/><strong>Este finde</strong><span>Planes del finde</span></button></div></section>\n    <section className="home-target-section"><div className="home-target-head home-target-head-sub"><div><h2>Personas compatibles</h2><p>Gente con tus mismos intereses</p></div><button onClick={()=>browse('people')}>Ver todas <ChevronRight/></button></div><div className="home-target-people">{compatiblePeople.map(person=><article key={person.name}><div className="home-target-person-photo"><img loading="lazy" decoding="async" src={person.image} alt={person.name}/><b>{person.match}</b></div><strong><i/>{person.name}, {person.age}</strong><span>{person.tags.join(' · ')}</span></article>)}</div></section>
    <section className="home-target-section"><div className="home-target-head home-target-head-sub"><div><h2>Escapadas y eventos</h2><p>Planes más allá de tu ciudad</p></div><button onClick={()=>browse('escapes')}>Ver todas <ChevronRight/></button></div><div className="home-target-escapes">{homeEscapes.map(item=><article key={item.title} role="button" tabIndex={0} onClick={()=>openEscape(item)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openEscape(item)}}}><img loading="lazy" decoding="async" src={item.image} alt={item.title}/><span className="home-target-card-shade"/><Heart className="home-target-heart"/><div><strong>{item.title}</strong><span><MapPin/>{item.subtitle}</span></div></article>)}</div></section>
    <section className="home-target-section home-benefits"><div className="home-target-head home-target-head-sub"><div><h2>Ventajas CONECTA</h2><p>Ofertas y experiencias seleccionadas</p></div><button onClick={()=>browse('benefits')}>Ver todas <ChevronRight/></button></div><div className="home-benefit-grid"><button type="button" onClick={()=>browse('benefits','Fitness')}><Dumbbell/><span><small>FITNESS</small><strong>Hasta -20%</strong><em>Gimnasios asociados</em></span></button><button type="button" onClick={()=>browse('benefits','Viajes')}><Tag/><span><small>VIAJES</small><strong>Hasta -15%</strong><em>Escapadas seleccionadas</em></span></button><button type="button" onClick={()=>browse('benefits','Gastronomía')}><Coffee/><span><small>GASTRONOMÍA</small><strong>2×1</strong><em>Locales seleccionados</em></span></button></div><span className="home-benefit-premium">EXCLUSIVO PREMIUM</span></section>
    <section className="premium-banner premium-card-version"><div><CreditCard/><span>CONECTA PREMIUM</span></div><div className="premium-mini-card"><CreditCard/><strong>CONECTA<br/>PREMIUM</strong></div><h2>Más planes, más conexiones</h2><p>Ofertas exclusivas · Viajes · Gimnasios · Experiencias · Más seguridad</p><button onClick={()=>browse('premium')}>Ver CONECTA Premium <ChevronRight/></button></section>
  </div>
}
