import { useEffect, useState } from 'react';
import { CalendarDays, ChevronLeft, Coffee, Dumbbell, Heart, MapPin, Music2, Search, Sparkles, Tag, Users } from 'lucide-react';
import { PremiumContent } from '../components/PremiumContent';
import { blockedNames, canUseLocation, loadPrivacySettings } from '../lib/privacy';
import { CategoryIcon } from '../components/CategoryIcon';
import { PlanCards } from '../components/PlanComponents';
import { categories, escapes, people, plans } from '../data/demoData';
import { filterExplorePlans, planIdentityKey } from '../lib/planLogic';
import { loadStored, saveStored, storageKeys } from '../lib/storage';
import type { ExploreFilter, HomeBrowseMode, Plan } from '../types';

const modeTitle:Record<HomeBrowseMode,string>={all:'Explorar planes',categories:'Categorías',near:'Descubre planes cerca de ti',today:'Planes de hoy',afternoon:'Esta tarde',tonight:'Esta noche',weekend:'Este finde',escapes:'Escapadas y eventos',people:'Personas compatibles',when:'¿Cuándo quieres salir?',benefits:'Ventajas CONECTA',premium:'CONECTA Premium',search:'Buscar planes'};
function plansFor(mode:HomeBrowseMode,category:string|null):Plan[]{if(category)return plans.filter(plan=>plan.category===category);if(mode==='near')return plans.slice(0,6);if(mode==='today')return plans.filter(plan=>plan.time.startsWith('Hoy'));if(mode==='afternoon')return plans.filter(plan=>/17:|18:|19:/.test(plan.time));if(mode==='tonight')return plans.filter(plan=>/20:|21:|22:/.test(plan.time));if(mode==='weekend')return plans.filter(plan=>/Sáb|Dom|Vie/.test(plan.time));return plans;}
function cleanMatch(value:string){const parsed=Number.parseInt(value.replace(/[^0-9]/g,''),10);return Number.isNaN(parsed)?value:`${Math.min(100,Math.max(0,parsed))}%`;}

const homeBenefits=[
  {name:'Fitness',label:'FITNESS',offer:'Hasta -20%',description:'Gimnasios asociados',Icon:Dumbbell},
  {name:'Viajes',label:'VIAJES',offer:'Hasta -15%',description:'Escapadas seleccionadas',Icon:Tag},
  {name:'Gastronomía',label:'GASTRONOMÍA',offer:'2×1',description:'Locales seleccionados',Icon:Coffee},
] as const;

export function HomeBrowseView({mode,category,onBack,onPlan,onBrowse,onMap,extraPlans=[]}:{mode:HomeBrowseMode;category:string|null;extraPlans?:Plan[];onBack:()=>void;onMap:()=>void;onPlan:(plan:Plan)=>void;onBrowse:(mode:HomeBrowseMode,category?:string|null)=>void;}){
  const title=category?category:modeTitle[mode];
  const [query,setQuery]=useState('');
  const [privacy]=useState(loadPrivacySettings);
  const [blocked]=useState(()=>blockedNames());
  const [premiumRequested,setPremiumRequested]=useState(()=>loadStored(storageKeys.premiumRequested,false));
  const requestPremium=()=>{setPremiumRequested(true);saveStored(storageKeys.premiumRequested,true)};
  const selectedBenefit=homeBenefits.find(item=>item.name===category);
  const showPlans=!['categories','escapes','people','when','benefits','premium'].includes(mode);
  const realFilter:ExploreFilter=['near','today','afternoon','tonight','weekend'].includes(mode)?mode as ExploreFilter:'all';
  const realPlans=filterExplorePlans(extraPlans,{timeFilter:realFilter,category,query:'',sortAsc:true});
  const visiblePlans=[...realPlans,...plansFor(mode,category)].filter(plan=>!query.trim()||`${plan.title} ${plan.category} ${plan.place}`.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')));
  const [favorites,setFavorites]=useState<string[]>(()=>loadStored(storageKeys.planFavorites,[]));
  const toggleFavorite=(plan:Plan)=>{const key=planIdentityKey(plan);const next=favorites.includes(key)?favorites.filter(item=>item!==key):[...favorites,key];setFavorites(next);saveStored(storageKeys.planFavorites,next);};
  useEffect(()=>{setQuery('');window.scrollTo({top:0,behavior:'auto'});},[mode,category]);
  return <div className="page home-browse-page home-browse-premium" data-home-screen={mode}>
    <nav className="home-browse-toolbar" aria-label="Navegación de Inicio"><button type="button" className="home-browse-return" onClick={onBack}><ChevronLeft/>Volver al Inicio</button>{category&&<button type="button" className="home-browse-return" onClick={()=>onBrowse(mode)}>{mode==='benefits'?'Todas las ventajas':'Todas las categorías'}</button>}{mode==='near'&&canUseLocation(privacy)&&<button type="button" className="home-browse-return" data-testid="map-entry" onClick={onMap}><MapPin/>Ver mapa</button>}</nav>
    <header className="home-browse-header"><div className="home-browse-heading"><span className="home-browse-kicker">CONECTA</span><h1>{title}</h1><p>{mode==='near'&&!category?'Descubre opciones desde Inicio':'Descubre, participa y vive más'}</p></div>{!['near','when','benefits','premium','search'].includes(mode)&&!category&&<span className="home-browse-location"><MapPin/>Tarragona</span>}</header>
    {mode==='search'&&<label className="home-browse-search"><Search/><input type="search" aria-label="Buscar en los planes" placeholder="Busca un plan, categoría o lugar" value={query} onChange={event=>setQuery(event.target.value)}/></label>}
    {mode==='when'&&<section className="now-section" aria-label="Cuándo quieres salir"><div className="quick-grid"><button type="button" onClick={()=>onBrowse('today')}><Sparkles/><strong>Ahora mismo</strong><span>Planes de hoy</span></button><button type="button" onClick={()=>onBrowse('afternoon')}><Coffee/><strong>Esta tarde</strong><span>Planes de tarde</span></button><button type="button" onClick={()=>onBrowse('tonight')}><Music2/><strong>Esta noche</strong><span>Planes nocturnos</span></button><button type="button" onClick={()=>onBrowse('weekend')}><CalendarDays/><strong>Este finde</strong><span>Planes del finde</span></button></div></section>}
    {mode==='benefits'&&<section className="home-benefits" aria-label="Ventajas CONECTA">{selectedBenefit?<div className="home-browse-benefit-detail"><selectedBenefit.Icon/><h2>{selectedBenefit.offer}</h2><p>{selectedBenefit.description}</p><p>Oferta presentada en el demo de CONECTA. Su disponibilidad y condiciones se confirmarán cuando se active el servicio.</p><button type="button" className="home-browse-return" onClick={()=>onBrowse('premium')}>Ver CONECTA Premium</button></div>:<div className="home-benefit-grid">{homeBenefits.map(({name,label,offer,description,Icon})=><button type="button" key={name} onClick={()=>onBrowse('benefits',name)}><Icon/><span><small>{label}</small><strong>{offer}</strong><em>{description}</em></span></button>)}</div>}<span className="home-benefit-premium">EXCLUSIVO PREMIUM</span></section>}
    {mode==='premium'&&<section className="settings-shell" aria-label="CONECTA Premium"><PremiumContent requested={premiumRequested} onRequest={requestPremium}/></section>}
    {mode==='categories'&&!category&&<section className="home-browse-grid home-browse-categories" aria-label="Categorías">{categories.map(([name,image])=><button type="button" key={name} onClick={()=>onBrowse('categories',name)}><img loading="lazy" decoding="async" src={image} alt=""/><span className="home-browse-category-label"><CategoryIcon name={name}/>{name}</span><b>›</b></button>)}</section>}
    {mode==='escapes'&&<section className="home-browse-grid home-browse-escapes" aria-label="Escapadas y eventos">{escapes.map(([name,date,image])=><article key={name} role="button" tabIndex={0} onClick={()=>onPlan({title:name,image,time:date,place:name,distance:'',spots:'8 plazas',category:'Viajes'})} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onPlan({title:name,image,time:date,place:name,distance:'',spots:'8 plazas',category:'Viajes'})}}}><img loading="lazy" decoding="async" src={image} alt=""/><div><strong>{name}</strong><span><MapPin/>{date}</span></div></article>)}</section>}
    {mode==='people'&&<section className="home-browse-grid home-browse-people" aria-label="Personas compatibles">{people.filter(person=>!blocked.has(person.name)).map(person=><article className="home-browse-person" key={person.name}><div className="home-browse-person-photo"><img loading="lazy" decoding="async" src={person.image} alt={`Foto de ${person.name}`}/><span>{cleanMatch(person.match)} compatible</span></div><div className="home-browse-person-body"><div className="home-browse-person-main"><strong>{person.name}, {person.age}</strong><span>{person.distance}</span></div><div className="home-browse-person-tags">{person.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><p>{person.bio}</p></div></article>)}</section>}
    {showPlans&&<section className="home-browse-plan-grid" aria-label={title}>{visiblePlans.map((plan,index)=><article className={`home-browse-plan-card home-browse-plan-card-${index%4}`} key={planIdentityKey(plan)} role="button" tabIndex={0} onClick={()=>onPlan(plan)} onKeyDown={event=>{if(event.target!==event.currentTarget)return;if(event.key==='Enter'||event.key===' '){event.preventDefault();onPlan(plan)}}}><div className="home-browse-plan-image"><img loading="lazy" decoding="async" src={plan.image} alt={plan.title}/><span className="home-browse-distance-badge"><MapPin/>{plan.distance||'Cerca'}</span><button type="button" className="home-browse-image-favorite" aria-label={`Guardar ${plan.title}`} aria-pressed={favorites.includes(planIdentityKey(plan))} onClick={event=>{event.stopPropagation();toggleFavorite(plan)}}><Heart fill={favorites.includes(planIdentityKey(plan))?'currentColor':'none'}/></button></div><div className="home-browse-plan-body"><span className="home-browse-category"><CategoryIcon name={plan.category}/>{plan.category}</span><div className="home-browse-plan-title"><strong>{plan.title}</strong></div><div className="home-browse-plan-meta"><span><CalendarDays/>{plan.time}</span><span><MapPin/>{plan.distance||plan.place}</span><span><Users/>{plan.spots}</span></div><button type="button" className="home-browse-plan-open" onClick={event=>{event.stopPropagation();onPlan(plan)}}>Ver plan <span>→</span></button></div></article>)}</section>}
    {showPlans&&!visiblePlans.length&&<p className="empty-state" role="status">No hay planes que coincidan con tu búsqueda.</p>}
    {mode==='categories'&&category&&(visiblePlans.length?<PlanCards items={visiblePlans} onPlan={onPlan}/>:<p className="empty-state">Todavía no hay planes en esta categoría.</p>)} 
  </div>;
}
