import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, LocateFixed, MapPin } from 'lucide-react';
import type { Plan } from '../types';

type Point={plan:Plan;lat:number;lng:number};
type LeafletWindow=Window&{L?:any};
type GeoRow={lat:string;lon:string};
const TARRAGONA:[number,number]=[41.1189,1.2445];
const geoCache=new Map<string,{lat:number;lng:number}|null>();

function loadLeaflet(){return new Promise<any>((resolve,reject)=>{const w=window as LeafletWindow;if(w.L)return resolve(w.L);if(!document.querySelector('link[data-conecta-leaflet]')){const link=document.createElement('link');link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';link.dataset.conectaLeaflet='1';document.head.appendChild(link)}const existing=document.querySelector('script[data-conecta-leaflet]') as HTMLScriptElement|null;if(existing){if((window as LeafletWindow).L)return resolve((window as LeafletWindow).L);existing.addEventListener('load',()=>resolve((window as LeafletWindow).L),{once:true});existing.addEventListener('error',()=>reject(new Error('Leaflet unavailable')),{once:true});return}const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.dataset.conectaLeaflet='1';script.onload=()=>resolve((window as LeafletWindow).L);script.onerror=()=>reject(new Error('Leaflet unavailable'));document.head.appendChild(script)})}

async function geocode(plan:Plan,signal:AbortSignal):Promise<Point|null>{if(Number.isFinite(plan.latitude)&&Number.isFinite(plan.longitude))return {plan,lat:plan.latitude!,lng:plan.longitude!};const place=plan.place?.trim();if(!place||place==='Lugar por confirmar'||place==='Mi ubicación')return null;const key=place.toLocaleLowerCase('es');if(geoCache.has(key)){const cached=geoCache.get(key);return cached?{plan,...cached}:null}try{const q=encodeURIComponent(`${place}, España`);const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=es&q=${q}`,{headers:{'Accept-Language':'es'},signal});if(!response.ok)return null;const rows=await response.json() as GeoRow[];const lat=Number(rows[0]?.lat),lng=Number(rows[0]?.lon);const value=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;geoCache.set(key,value);return value?{plan,...value}:null}catch(error){if((error as Error).name!=='AbortError')geoCache.set(key,null);return null}}

export function MapView({plans,onBack,onPlan}:{plans:Plan[];onBack:()=>void;onPlan:(plan:Plan)=>void}){const node=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const userMarkerRef=useRef<any>(null);const [selected,setSelected]=useState<Plan|null>(null);const [status,setStatus]=useState('Cargando mapa y ubicaciones…');
useEffect(()=>{let alive=true;let map:any;const controller=new AbortController();void(async()=>{const L=await loadLeaflet();if(!alive||!node.current)return;map=L.map(node.current,{zoomControl:false,preferCanvas:true}).setView(TARRAGONA,11);mapRef.current=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);const points:Point[]=[];for(const plan of plans){if(!alive)break;const point=await geocode(plan,controller.signal);if(point)points.push(point)}if(!alive)return;for(const point of points){const marker=L.marker([point.lat,point.lng]).addTo(map);marker.bindTooltip(point.plan.title,{direction:'top'});marker.on('click',()=>setSelected(point.plan))}if(points.length){const bounds=L.latLngBounds(points.map(p=>[p.lat,p.lng]));map.fitBounds(bounds.pad(.18),{maxZoom:14})}setStatus(points.length?`${points.length} ${points.length===1?'plan ubicado':'planes ubicados'} en el mapa`:'Todavía no hay planes con ubicación válida')})().catch(()=>{if(alive)setStatus('No se ha podido cargar el mapa. Comprueba la conexión.')});return()=>{alive=false;controller.abort();if(map){map.remove();mapRef.current=null}}},[plans]);
const locate=()=>{if(!navigator.geolocation){setStatus('Este dispositivo no ofrece geolocalización');return}setStatus('Buscando tu ubicación…');navigator.geolocation.getCurrentPosition(pos=>{const map=mapRef.current;if(!map)return;const L=(window as LeafletWindow).L;const coords:[number,number]=[pos.coords.latitude,pos.coords.longitude];map.flyTo(coords,15);if(L){userMarkerRef.current?.remove?.();userMarkerRef.current=L.circleMarker(coords,{radius:9,weight:4,fillOpacity:1}).addTo(map).bindTooltip('Tu ubicación')}setStatus('Ubicación actual mostrada')},error=>setStatus(error.code===1?'Ubicación no autorizada':'No se ha podido obtener tu ubicación'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
return <div className="real-map-page"><div ref={node} className="real-map-canvas"/><header className="real-map-header"><button onClick={onBack} aria-label="Volver"><ChevronLeft/></button><div><strong>Mapa de planes</strong><span>{status}</span></div></header><button className="real-map-locate" onClick={locate}><LocateFixed/> Mi ubicación</button>{selected&&<button className="real-map-plan" onClick={()=>onPlan(selected)}><img src={selected.image} alt=""/><span><small>{selected.time}</small><strong>{selected.title}</strong><em><MapPin/>{selected.place}</em></span><b>Ver plan</b></button>}</div>}
