import { loadLeaflet } from '../lib/leaflet';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, LocateFixed, MapPin, Search, X } from 'lucide-react';
import type { Plan } from '../types';

type Point={plan:Plan;lat:number;lng:number};
type LeafletWindow=Window&{L?:any};
type GeoRow={lat:string;lon:string};
const TARRAGONA:[number,number]=[41.1189,1.2445];
const geoCache=new Map<string,{lat:number;lng:number}|null>();
async function geocode(plan:Plan,signal:AbortSignal):Promise<Point|null>{if(Number.isFinite(plan.latitude)&&Number.isFinite(plan.longitude))return {plan,lat:plan.latitude!,lng:plan.longitude!};const place=plan.place?.trim();if(!place||place==='Lugar por confirmar'||place==='Mi ubicación'||place==='Ubicación actual')return null;const key=place.toLocaleLowerCase('es');if(geoCache.has(key)){const cached=geoCache.get(key);return cached?{plan,...cached}:null}try{const q=encodeURIComponent(`${place}, España`);const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=es&q=${q}`,{headers:{'Accept-Language':'es'},signal});if(!response.ok)return null;const rows=await response.json() as GeoRow[];const lat=Number(rows[0]?.lat),lng=Number(rows[0]?.lon);const value=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;geoCache.set(key,value);return value?{plan,...value}:null}catch(error){if((error as Error).name!=='AbortError')geoCache.set(key,null);return null}}
export function MapView({plans,onBack,onPlan}:{plans:Plan[];onBack:()=>void;onPlan:(plan:Plan)=>void}){const node=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const userMarkerRef=useRef<any>(null);const [selected,setSelected]=useState<Plan|null>(null);const [status,setStatus]=useState('Cargando mapa y ubicaciones…');const [query,setQuery]=useState('');const [points,setPoints]=useState<Point[]>([]);const [panelOpen,setPanelOpen]=useState(true);
const cities=useMemo(()=>{const grouped=new Map<string,Point[]>();for(const point of points){const name=point.plan.place?.trim()||'Sin ubicación';const list=grouped.get(name)||[];list.push(point);grouped.set(name,list)}return [...grouped.entries()].map(([name,items])=>({name,items,lat:items.reduce((s,p)=>s+p.lat,0)/items.length,lng:items.reduce((s,p)=>s+p.lng,0)/items.length})).filter(city=>city.name.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>b.items.length-a.items.length)},[points,query]);
useEffect(()=>{let alive=true;let map:any;const controller=new AbortController();void(async()=>{const L=await loadLeaflet();if(!alive||!node.current)return;map=L.map(node.current,{zoomControl:false,preferCanvas:true}).setView(TARRAGONA,9);mapRef.current=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);const found:Point[]=[];for(const plan of plans){if(!alive)break;const point=await geocode(plan,controller.signal);if(point)found.push(point)}if(!alive)return;setPoints(found);for(const point of found){const marker=L.circleMarker([point.lat,point.lng],{radius:8,weight:3,fillOpacity:.92}).addTo(map);const tooltip=document.createElement('span');tooltip.textContent=point.plan.title;marker.bindTooltip(tooltip,{direction:'top'});marker.on('click',()=>setSelected(point.plan))}if(found.length){const bounds=L.latLngBounds(found.map(p=>[p.lat,p.lng]));map.fitBounds(bounds.pad(.25),{maxZoom:11})}setStatus(found.length?`${found.length} ${found.length===1?'plan disponible':'planes disponibles'} en el mapa`:'Todavía no hay planes con ubicación válida')})().catch(()=>{if(alive)setStatus('No se ha podido cargar el mapa. Comprueba la conexión.')});return()=>{alive=false;controller.abort();if(map){map.remove();mapRef.current=null}}},[plans]);
const locate=()=>{if(!navigator.geolocation){setStatus('Este dispositivo no ofrece geolocalización');return}setStatus('Buscando tu ubicación…');navigator.geolocation.getCurrentPosition(pos=>{const map=mapRef.current;if(!map)return;const L=(window as LeafletWindow).L;const coords:[number,number]=[pos.coords.latitude,pos.coords.longitude];map.flyTo(coords,14);if(L){userMarkerRef.current?.remove?.();userMarkerRef.current=L.circleMarker(coords,{radius:9,weight:4,fillOpacity:1}).addTo(map).bindTooltip('Tu ubicación')}setStatus('Ubicación actual mostrada')},error=>setStatus(error.code===1?'Ubicación no autorizada':'No se ha podido obtener tu ubicación'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
const focusCity=(city:(typeof cities)[number])=>{mapRef.current?.flyTo([city.lat,city.lng],12);setPanelOpen(false)};
return <div className="real-map-page"><div ref={node} className="real-map-canvas"/><header className="real-map-header"><button onClick={onBack} aria-label="Volver"><ChevronLeft/></button><div><strong>Mapa de planes</strong><span>{status}</span></div></header><button className="real-map-locate" onClick={locate}><LocateFixed/> Mi ubicación</button><div className="real-map-search"><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPanelOpen(true)}} placeholder="Buscar ciudad o zona…"/>{query&&<button onClick={()=>setQuery('')} aria-label="Limpiar"><X/></button>}</div>{panelOpen&&<section className="real-map-cities"><div className="real-map-cities-head"><div><MapPin/><span><strong>Ciudades y zonas</strong><small>Planes disponibles con ubicación real</small></span></div><button onClick={()=>setPanelOpen(false)}>Ocultar</button></div><div className="real-map-city-list">{cities.length?cities.map(city=><button key={city.name} onClick={()=>focusCity(city)}><span><strong>{city.name}</strong><small>{city.items.length} {city.items.length===1?'plan':'planes'}</small></span><b>{city.items.length}</b><ChevronRight/></button>):<p>No hay ubicaciones que coincidan con la búsqueda.</p>}</div></section>}{!panelOpen&&<button className="real-map-show-list" onClick={()=>setPanelOpen(true)}><MapPin/> Ver ciudades y planes</button>}{selected&&<button className="real-map-plan" onClick={()=>onPlan(selected)}><img src={selected.image} alt=""/><span><small>{selected.time}</small><strong>{selected.title}</strong><em><MapPin/>{selected.place}</em></span><b>Ver plan</b></button>}</div>}
