import { useState } from 'react';
import { Bell, ChevronLeft, ChevronRight, CircleHelp, Database, Download, Eye, Globe, LockKeyhole, LogOut, Mail, MapPinned, MessageCircleMore, MoonStar, ShieldCheck, Smartphone, Sparkles, UserRound, UserX, BadgeCheck } from 'lucide-react';

type Screen='root'|'security'|'privacy'|'notifications'|'help'|'premium';
type ToggleKey='messages'|'requests'|'planUpdates'|'reminders'|'news'|'offers';

function Header({title,subtitle,onBack}:{title:string;subtitle:string;onBack?:()=>void}){return <div className="settings-header">{onBack?<button className="settings-back" onClick={onBack}><ChevronLeft/></button>:<span className="settings-back placeholder"/>}<div className="settings-header-copy"><h1>{title}</h1><p>{subtitle}</p></div><span className="settings-back placeholder"/></div>}
function Row({icon:Icon,title,subtitle,onClick,danger=false}:{icon:any;title:string;subtitle:string;onClick?:()=>void;danger?:boolean}){return <button className={`settings-row ${danger?'is-danger':''}`} onClick={onClick}><span className="settings-row-icon"><Icon/></span><span className="settings-row-copy"><strong>{title}</strong><small>{subtitle}</small></span><ChevronRight/></button>}
function ToggleRow({label,sublabel,checked,onToggle}:{label:string;sublabel:string;checked:boolean;onToggle:()=>void}){return <div className="settings-toggle-row"><div className="settings-toggle-copy"><strong>{label}</strong><small>{sublabel}</small></div><button className={`settings-switch ${checked?'is-on':''}`} onClick={onToggle}><span/></button></div>}

export function SettingsView(){
  const [screen,setScreen]=useState<Screen>('root');
  const [toggles,setToggles]=useState<Record<ToggleKey,boolean>>({messages:true,requests:true,planUpdates:true,reminders:true,news:true,offers:true});
  const [frequency,setFrequency]=useState<'daily'|'weekly'|'important'>('daily');
  const toggle=(k:ToggleKey)=>setToggles(v=>({...v,[k]:!v[k]}));

  if(screen==='security')return <div className="page settings-page"><div className="settings-shell"><Header title="Seguridad" subtitle="Mantén tu cuenta protegida" onBack={()=>setScreen('root')}/><div className="settings-list-card"><Row icon={LockKeyhole} title="Contraseña" subtitle="Última actualización: hace 3 meses"/><Row icon={ShieldCheck} title="Verificación en dos pasos" subtitle="Añade una capa extra de seguridad"/><Row icon={Mail} title="Verificación de email" subtitle="fernando96@gmail.com · Verificado"/><Row icon={Smartphone} title="Verificación de teléfono" subtitle="+34 6XX XXX XXX · Verificado"/><Row icon={BadgeCheck} title="Apple" subtitle="Conectado"/><Row icon={Globe} title="Google" subtitle="Conectado"/><Row icon={Database} title="Sesiones activas" subtitle="Gestiona dónde has iniciado sesión"/></div><button className="settings-danger-cta"><LogOut/><span><strong>Cerrar todas las sesiones</strong><small>Cierra sesión en todos tus dispositivos</small></span></button></div></div>;

  if(screen==='privacy')return <div className="page settings-page"><div className="settings-shell"><Header title="Privacidad" subtitle="Tú decides qué compartir" onBack={()=>setScreen('root')}/><div className="settings-list-card"><Row icon={Eye} title="Visibilidad del perfil" subtitle="Quién puede ver tu perfil"/><Row icon={BadgeCheck} title="Quién puede ver tus planes" subtitle="Todos los usuarios"/><Row icon={MapPinned} title="Control de ubicación" subtitle="Cuándo se muestra tu ubicación"/><Row icon={MessageCircleMore} title="Quién puede enviarte mensajes" subtitle="Solo usuarios conectados"/><Row icon={UserRound} title="Solicitudes de conexión" subtitle="Quién puede enviarte solicitudes"/><Row icon={UserX} title="Usuarios bloqueados" subtitle="Gestiona usuarios bloqueados"/><Row icon={Database} title="Datos y actividad" subtitle="Gestiona tu información"/><Row icon={Download} title="Descargar mis datos" subtitle="Recibe una copia de tu información"/><Row icon={LogOut} title="Eliminar cuenta" subtitle="Elimina tu cuenta y todos tus datos" danger/></div></div></div>;

  if(screen==='notifications')return <div className="page settings-page"><div className="settings-shell"><Header title="Notificaciones" subtitle="Elige qué quieres recibir" onBack={()=>setScreen('root')}/><div className="settings-block"><ToggleRow label="Nuevos mensajes" sublabel="Cuando recibas un mensaje" checked={toggles.messages} onToggle={()=>toggle('messages')}/><ToggleRow label="Solicitudes de conexión" sublabel="Nuevas solicitudes" checked={toggles.requests} onToggle={()=>toggle('requests')}/><ToggleRow label="Actualizaciones de planes" sublabel="Cambios en tus planes" checked={toggles.planUpdates} onToggle={()=>toggle('planUpdates')}/><ToggleRow label="Recordatorios" sublabel="Avisos de tus próximos planes" checked={toggles.reminders} onToggle={()=>toggle('reminders')}/><ToggleRow label="Novedades de la app" sublabel="Noticias y mejoras" checked={toggles.news} onToggle={()=>toggle('news')}/><ToggleRow label="Ofertas y promociones" sublabel="Solo para usuarios Premium" checked={toggles.offers} onToggle={()=>toggle('offers')}/></div><div className="settings-block"><div className="settings-block-title">Frecuencia</div>{[['daily','Resumen diario','Recibe un resumen al final del día'],['weekly','Resumen semanal','Un resumen cada semana'],['important','Solo notificaciones importantes','Solo lo esencial']].map(([key,title,sub])=><button key={key} className={`settings-frequency-option ${frequency===key?'is-active':''}`} onClick={()=>setFrequency(key as any)}><span className="settings-frequency-copy"><strong>{title}</strong><small>{sub}</small></span><span className="settings-radio"><span/></span></button>)}</div></div></div>;

  if(screen==='help')return <div className="page settings-page"><div className="settings-shell"><Header title="Centro de ayuda" subtitle="Guías, soporte y contacto" onBack={()=>setScreen('root')}/><div className="settings-list-card"><Row icon={CircleHelp} title="Guía de CONECTA" subtitle="Cómo usar la app"/><Row icon={ShieldCheck} title="Normas de la comunidad" subtitle="Nuestras reglas"/><Row icon={BadgeCheck} title="Seguridad en la app" subtitle="Consejos y buenas prácticas"/><Row icon={LockKeyhole} title="Privacidad" subtitle="Cómo protegemos tus datos"/><Row icon={Database} title="Condiciones de uso" subtitle="Términos y condiciones"/><Row icon={Mail} title="Soporte técnico" subtitle="soporte@conectaapp.com"/><Row icon={MessageCircleMore} title="Enviar feedback" subtitle="Cuéntanos tu opinión"/></div><div className="settings-support-box"><div><strong>¿Necesitas ayuda?</strong><small>Nuestro equipo está aquí para ti.</small></div><button>Contactar soporte</button></div></div></div>;

  if(screen==='premium')return <div className="page settings-page"><div className="settings-shell"><Header title="Conecta Premium" subtitle="Más planes. Más personas. Más vida." onBack={()=>setScreen('root')}/><div className="premium-hero-card"><div className="premium-card-visual"><div className="premium-card-chip"/><div className="premium-card-brand">CONECTA</div></div><div className="premium-hero-copy"><h2>Vive más experiencias</h2><p>Conecta Premium te da acceso a más oportunidades para hacer planes y conocer gente increíble.</p></div></div><div className="premium-benefits-list">{[['1','Más visibilidad','Tu perfil llega a más personas'],['2','Planes prioritarios','Destaca tus planes en la app'],['3','Ofertas exclusivas','Accede a promociones especiales'],['4','Filtros avanzados','Encuentra personas afines'],['5','Apoya la comunidad','Ayúdanos a seguir mejorando CONECTA']].map(([n,t,s])=><div key={n} className="premium-benefit-row"><span className="premium-number">{n}</span><div><strong>{t}</strong><small>{s}</small></div></div>)}</div><button className="premium-main-cta">Hazte Premium <ChevronRight/></button><p className="premium-footnote">Desde 4,99 €/mes · Cancela cuando quieras</p></div></div>;

  return <div className="page settings-page"><div className="settings-shell"><Header title="Ajustes" subtitle="Personaliza tu experiencia en CONECTA"/><div className="settings-search">Buscar en ajustes...</div><div className="settings-list-card"><Row icon={UserRound} title="Mi cuenta" subtitle="Datos personales y preferencias"/><Row icon={ShieldCheck} title="Seguridad" subtitle="Contraseña y verificación" onClick={()=>setScreen('security')}/><Row icon={LockKeyhole} title="Privacidad" subtitle="Controla tu información" onClick={()=>setScreen('privacy')}/><Row icon={Bell} title="Notificaciones" subtitle="Alertas y recordatorios" onClick={()=>setScreen('notifications')}/><Row icon={MoonStar} title="Apariencia" subtitle="Tema y modo oscuro"/><Row icon={Globe} title="Idioma" subtitle="Español"/><Row icon={CircleHelp} title="Centro de ayuda" subtitle="Guías y soporte" onClick={()=>setScreen('help')}/><Row icon={Sparkles} title="Sobre CONECTA" subtitle="Versión 2.0.0"/></div><button className="settings-premium-entry" onClick={()=>setScreen('premium')}><div className="settings-premium-entry-card"><div className="settings-premium-entry-chip"/></div><div className="settings-premium-entry-copy"><strong>Conecta Premium</strong><small>Vive más experiencias</small></div><ChevronRight/></button></div></div>;
}
