import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const APP_ORIGIN="https://fernandoexposito96.github.io";
const cors={"Access-Control-Allow-Origin":APP_ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}});
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const REPO="fernandoexposito96/Proyecto-CONECTA",WORKFLOW="diagnostic-hourly.yml";
const PUBLIC_REQUESTER="29afc43a-dc12-43c6-ba96-5da1c92c11f9";

async function verifiedUserId(req:Request){
  const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");
  if(!token)return "";
  const {data:{user},error}=await db.auth.getUser(token);
  return error?"":user?.id||"";
}
async function isAdmin(id:string){if(!id)return false;const {data}=await db.from("robot_admins").select("user_id").eq("user_id",id).maybeSingle();return!!data}
function configured(){return Boolean(Deno.env.get("CONECTA_GITHUB_TOKEN")||(Deno.env.get("GITHUB_APP_ID")&&Deno.env.get("GITHUB_APP_INSTALLATION_ID")&&Deno.env.get("GITHUB_APP_PRIVATE_KEY")))}
function bytesFromB64(s:string){const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function derLen(n:number){if(n<128)return Uint8Array.of(n);const a=[];while(n>0){a.unshift(n&255);n>>=8}return Uint8Array.of(0x80|a.length,...a)}
function concat(...parts:Uint8Array[]){const n=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function pemToPkcs8(pem:string){const normalized=pem.replace(/\\n/g,"\n").trim();if(normalized.includes("BEGIN PRIVATE KEY")){return bytesFromB64(normalized.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,""))}if(!normalized.includes("BEGIN RSA PRIVATE KEY"))throw new Error("github_private_key_format");const pkcs1=bytesFromB64(normalized.replace(/-----BEGIN RSA PRIVATE KEY-----|-----END RSA PRIVATE KEY-----|\s/g,""));const version=Uint8Array.of(0x02,0x01,0x00);const alg=Uint8Array.of(0x30,0x0d,0x06,0x09,0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x01,0x05,0x00);const octet=concat(Uint8Array.of(0x04),derLen(pkcs1.length),pkcs1);const body=concat(version,alg,octet);return concat(Uint8Array.of(0x30),derLen(body.length),body)}
function b64url(v:Uint8Array|string){const bytes=typeof v==="string"?new TextEncoder().encode(v):v;let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
async function githubToken(){const pat=Deno.env.get("CONECTA_GITHUB_TOKEN");if(pat)return pat;const appId=Deno.env.get("GITHUB_APP_ID"),install=Deno.env.get("GITHUB_APP_INSTALLATION_ID"),key=Deno.env.get("GITHUB_APP_PRIVATE_KEY");if(!appId||!install||!key)return"";const now=Math.floor(Date.now()/1000),h=b64url(JSON.stringify({alg:"RS256",typ:"JWT"})),p=b64url(JSON.stringify({iat:now-30,exp:now+540,iss:appId}));const k=await crypto.subtle.importKey("pkcs8",pemToPkcs8(key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5",k,new TextEncoder().encode(`${h}.${p}`)));const jwt=`${h}.${p}.${b64url(sig)}`;const r=await fetch(`https://api.github.com/app/installations/${install}/access_tokens`,{method:"POST",headers:{Authorization:`Bearer ${jwt}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"conecta-robot"}});if(!r.ok)throw new Error(`github_app_auth_${r.status}`);return String((await r.json()).token||"")}
async function dispatch(jobId:string,mode:string){let token="";try{token=await githubToken()}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e)}}if(!token)return{ok:false,error:"github_credentials_missing"};const r=await fetch(`https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW}/dispatches`,{method:"POST",headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json","User-Agent":"conecta-robot"},body:JSON.stringify({ref:"main"})});return r.ok?{ok:true}:{ok:false,error:`github_${r.status}:${await r.text()}`}}
async function reconcileJobs(){if(!configured())return;let token="";try{token=await githubToken()}catch{return}if(!token)return;const {data:pending}=await db.from("robot_scan_jobs").select("*").in("status",["queued","dispatching","running"]).order("requested_at",{ascending:false}).limit(20);if(!pending?.length)return;const r=await fetch(`https://api.github.com/repos/${REPO}/actions/workflows/${WORKFLOW}/runs?branch=main&event=workflow_dispatch&per_page=50`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"conecta-robot"}});if(!r.ok)return;const runs=(await r.json()).workflow_runs||[];for(const job of pending){const started=new Date(job.requested_at).getTime();const run=runs.find((x:any)=>new Date(x.created_at).getTime()>=started-30000);if(!run)continue;let status="running";if(run.status==="completed"){if(run.conclusion==="success")status="completed";else if(run.conclusion==="cancelled")status="cancelled";else status="failed"}const patch:any={status,github_run_id:run.id,github_run_url:run.html_url,head_sha:run.head_sha,started_at:job.started_at||run.run_started_at||run.created_at};if(run.status==="completed")patch.completed_at=run.updated_at||new Date().toISOString();if(status==="failed")patch.error_message=`GitHub conclusion: ${run.conclusion||"failure"}`;await db.from("robot_scan_jobs").update(patch).eq("id",job.id)}}
async function newJob(userId:string,mode="full",reason="manual"){const {data:active}=await db.from("robot_scan_jobs").select("*").in("status",["dispatching","running"]).order("requested_at",{ascending:false}).limit(1);if(active?.length)return active[0];if(reason==="manual_public"){const cutoff=new Date(Date.now()-60000).toISOString();const {data:recent}=await db.from("robot_scan_jobs").select("*").gte("requested_at",cutoff).order("requested_at",{ascending:false}).limit(1);if(recent?.length)return recent[0]}const {data,error}=await db.from("robot_scan_jobs").insert({requested_by:userId,repository:REPO,branch:"main",scan_mode:mode,reason,status:"dispatching"}).select("*").single();if(error)throw error;const sent=await dispatch(data.id,mode);if(!sent.ok){await db.from("robot_scan_jobs").update({status:"failed",error_message:sent.error,completed_at:new Date().toISOString()}).eq("id",data.id);throw new Error(sent.error)}await db.from("robot_scan_jobs").update({status:"running",started_at:new Date().toISOString()}).eq("id",data.id);return{...data,status:"running"}}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const origin=req.headers.get("origin");if(origin&&origin!==APP_ORIGIN)return json({error:"origin_not_allowed"},403);try{const b=await req.json().catch(()=>({})),action=String(b.action||"status");const uid=await verifiedUserId(req);const admin=await isAdmin(uid);if(action==="status"){await reconcileJobs();const [{data:settings},{data:jobs}]=await Promise.all([db.from("robot_settings").select("*").eq("id","conecta-main").single(),db.from("robot_scan_jobs").select("*").order("requested_at",{ascending:false}).limit(20)]);return json({settings,jobs,credentialsReady:configured(),repo:REPO,workflow:WORKFLOW})}if(action==="scan_now"){if(!uid)return json({error:"unauthorized"},401);if(!configured())return json({error:"github_credentials_missing",credentialsReady:false},503);const {data:s}=await db.from("robot_settings").select("*").eq("id","conecta-main").single();if(!s?.enabled)return json({error:"robot_off"},409);const requester=admin&&uid?uid:PUBLIC_REQUESTER;return json({job:await newJob(requester,String(b.scan_mode||s.scan_mode||"full"),admin?"manual":"manual_public"),credentialsReady:true})}if(action==="set_power"){if(!admin)return json({error:"forbidden"},403);const enabled=!!b.enabled;const now=new Date().toISOString();if(!enabled){const {data,error}=await db.from("robot_settings").update({enabled:false,updated_by:uid,updated_at:now,last_disabled_at:now}).eq("id","conecta-main").select("*").single();if(error)throw error;return json({settings:data,job:null,credentialsReady:configured()})}if(!configured())return json({error:"github_credentials_missing",credentialsReady:false},503);let job=null;if(b.scan_on_enable!==false)job=await newJob(uid,String(b.scan_mode||"full"),"power_on");const {data,error}=await db.from("robot_settings").update({enabled:true,updated_by:uid,updated_at:now,last_enabled_at:now}).eq("id","conecta-main").select("*").single();if(error)throw error;return json({settings:data,job,credentialsReady:true})}return json({error:"unknown_action"},400)}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
