import { useEffect, useRef, useState } from 'react';
import type { Plan } from '../types';

type LeafletWindow=Window&{L?:any};
type GeoRow={lat:string;lon:string};
type Point={plan:Plan;lat:number;lng:number};
const DEFAULT_CENTER:[number,number]=[41.1189,1.2445];
const cache=new Map<string,{lat:number;lng:number}|null>();

function loadLeaflet(){return new Promise<any>((resolve,reject)=>{const w=window as LeafletWindow;if(w.L)return resolve(w.L);if(!document.querySelector('link[data-conecta-leaflet]')){const link=document.createElement('link');link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';link.dataset.conectaLeaflet='1';document.head.appendChild(link)}const existing=document.querySelector('script[data-conecta-leaflet]') as HTMLScriptElement|null;if(existing){existing.addEventListener('load',()=>resolve((window as LeafletWindow).L),{once:true});existing.addEventListener('error',()=>reject(new Error('Leaflet unavailable')),{once:true});return}const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';script.dataset.conectaLeaflet='1';script.onload=()=>resolve((window as LeafletWindow).L);script.onerror=()=>reject(new Error('Leaflet unavailable'));document.head.appendChild(script)})}
async function pointFor(plan:Plan,signal:AbortSignal):Promise<Point|null>{if(Number.isFinite(plan.latitude)&&Number.isFinite(plan.longitude))return{plan,lat:plan.latitude!,lng:plan.longitude!};const place=plan.place?.trim();if(!place||place==='Lugar por confirmar'||place==='Mi ubicación'||place==='Ubicación actual')return null;const key=place.toLocaleLowerCase('es');if(cache.has(key)){const hit=cache.get(key);return hit?{plan,...hit}:null}try{const q=encodeURIComponent(`${place}, España`);const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=es&q=${q}`,{headers:{'Accept-Language':'es'},signal});if(!response.ok)return null;const rows=await response.json() as GeoRow[];const lat=Number(rows[0]?.lat),lng=Number(rows[0]?.lon);const value=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null;cache.set(key,value);return value?{plan,...value}:null}catch(error){if((error as Error).name!=='AbortError')cache.set(key,null);return null}}

export function HomeRealMap({plans,onPlan}:{plans:Plan[];onPlan:(plan:Plan)=>void}){const node=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const [count,setCount]=useState(0);useEffect(()=>{let alive=true;let map:any;const controller=new AbortController();void(async()=>{const L=await loadLeaflet();if(!alive||!node.current)return;map=L.map(node.current,{zoomControl:false,attributionControl:false,dragging:true,scrollWheelZoom:false,doubleClickZoom:true,touchZoom:true}).setView(DEFAULT_CENTER,11);mapRef.current=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const points:Point[]=[];for(const plan of plans){if(!alive)break;const point=await pointFor(plan,controller.signal);if(point)points.push(point)}if(!alive)return;points.forEach(point=>{const marker=L.circleMarker([point.lat,point.lng],{radius:9,weight:3,fillOpacity:.9}).addTo(map);marker.bindTooltip(`<b>${point.plan.title}</b><br>${point.plan.place}`,{direction:'top'});marker.on('click',()=>onPlan(point.plan))});if(points.length)map.fitBounds(L.latLngBounds(points.map(p=>[p.lat,p.lng])).pad(.2),{maxZoom:13});setCount(points.length);setTimeout(()=>map.invalidateSize(),0)})().catch(()=>setCount(0));return()=>{alive=false;controller.abort();if(map){map.remove();mapRef.current=null}}},[plans,onPlan]);return <div className="home-real-map-wrap"><div ref={node} className="home-real-map" aria-label="Mapa real de planes y eventos"/><span className="home-real-map-count">{count?`${count} ubicados`:'Buscando ubicaciones…'}</span></div>}
