import { useEffect, useState } from 'react';
import { BottomNav, Header, Sidebar } from './components/AppNavigation';
import type { ChatContact } from './components/explore/PersonDetailCard';import { PlanDetail } from './components/PlanComponents';import { fetchSharedPlans } from './lib/cloud';import { acceptPlanInvite, clearInviteFromUrl, inviteCodeFromUrl } from './lib/inviteBackend';import { fetchUnreadNotificationCount } from './lib/notificationsBackend';import { createRealPlan, fetchRealPlans } from './lib/realPlansBackend';import { loadStored, saveStored, storageKeys } from './lib/storage';import type { ExploreFilter, HomeBrowseMode, Plan, View } from './types';
import { CalendarView } from './views/CalendarView';import { ChatView } from './views/ChatView';import { CreatePlanView } from './views/CreatePlanView';import { ExploreView } from './views/ExploreView';import { HomeBrowseView } from './views/HomeBrowseView';import { HomeView } from './views/HomeView';import { MapView } from './views/MapView';import { NotificationsView } from './views/NotificationsView';import { ProfileEnhancedView } from './views/ProfileEnhancedView';import { SettingsView } from './views/SettingsView';
const planKey=(plan:Plan)=>plan.backendId?`backend:${plan.backendId}`:`${plan.title}|${plan.time}|${plan.place}`;const mergePlans=(a:Plan[],b:Plan[])=>{const seen=new Set<string>();return [...a,...b].filter(p=>{const k=planKey(p);if(seen.has(k))return false;seen.add(k);return true})};
export default function App(){const [view,setView]=useState<View>('Inicio');const [selected,setSelected]=useState<Plan|null>(null);const [planReturnView,setPlanReturnView]=useState<View>('Inicio');const [createdPlans,setCreatedPlans]=useState<Plan[]>(()=>loadStored(storageKeys.createdPlans,[]));const [exploreFilter,setExploreFilter]=useState<ExploreFilter>('near');const [exploreCategory,setExploreCategory]=useState<string|null>(null);const [homeBrowseMode,setHomeBrowseMode]=useState<HomeBrowseMode>('all');const [homeBrowseCategory,setHomeBrowseCategory]=useState<string|null>(null);const [chatTarget,setChatTarget]=useState<ChatContact|null>(null);const [planChatTarget,setPlanChatTarget]=useState<string|null>(null);const [unreadNotifications,setUnreadNotifications]=useState(0);
useEffect(()=>{const url=new URL(window.location.href);const s=url.searchParams.get('shortcut');if(s==='create-plan')setView('Crear');if(s==='chat')setView('Chat');if(s==='now'){setHomeBrowseMode('today');setView('HomeBrowse')}if(s){url.searchParams.delete('shortcut');window.history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`)}},[]);useEffect(()=>saveStored(storageKeys.createdPlans,createdPlans),[createdPlans]);
useEffect(()=>{let active=true;void Promise.allSettled([fetchRealPlans(),fetchSharedPlans()]).then(r=>{if(!active)return;const real=r[0].status==='fulfilled'?r[0].value:[];const shared=r[1].status==='fulfilled'?r[1].value:[];setCreatedPlans(local=>mergePlans(real,mergePlans(shared,local.filter(p=>!p.backendId))))});return()=>{active=false}},[]);
useEffect(()=>{const code=inviteCodeFromUrl();if(!code)return;let active=true;void acceptPlanInvite(code).then(async id=>{const real=await fetchRealPlans();if(!active)return;setCreatedPlans(l=>mergePlans(real,l));const p=real.find(x=>x.backendId===id);if(p){setPlanReturnView('Explora');setSelected(p);setView('Plan')}clearInviteFromUrl()}).catch(e=>console.warn('CONECTA invite acceptance failed',e));return()=>{active=false}},[]);useEffect(()=>{let active=true;void fetchUnreadNotificationCount().then(n=>{if(active)setUnreadNotifications(n)}).catch(()=>{});return()=>{active=false}},[]);useEffect(()=>{if(view!=='Plan')setSelected(null);window.scrollTo({top:0,left:0,behavior:'auto'})},[view]);
const openHomeBrowse=(mode:HomeBrowseMode,category:string|null=null)=>{if(mode==='near'){setView('Mapa');return}setHomeBrowseMode(mode);setHomeBrowseCategory(category);setView('HomeBrowse')};const openContactChat=(contact:ChatContact)=>{setSelected(null);setPlanChatTarget(null);setChatTarget(contact);setView('Chat')};const openChat=(name?:string,planId?:string)=>{setSelected(null);setChatTarget(name?{name}:null);setPlanChatTarget(planId?`plan:${planId}`:null);setView('Chat')};const openPlan=(plan:Plan,returnView:View)=>{setPlanReturnView(returnView);setSelected(plan);setView('Plan')};const closePlan=()=>{setSelected(null);setView(planReturnView)};const addCreatedPlan=async(plan:Plan)=>{setExploreFilter('all');setExploreCategory(null);try{const real=await createRealPlan(plan);setCreatedPlans(p=>mergePlans([real],p.filter(x=>planKey(x)!==planKey(plan))));return true}catch(e){console.warn('CONECTA real plan publish unavailable',e);setCreatedPlans(p=>mergePlans([plan],p));return false}};const navigationView=view==='Plan'?planReturnView:view==='Mapa'?'Inicio':view;
return <div className="app-shell"><Sidebar view={view} activeView={navigationView} setView={setView}/><main><Header view={view} setView={setView} unreadNotifications={unreadNotifications}/><div className="content">{view==='Inicio'&&<HomeView setView={setView} onPlan={p=>openPlan(p,'Inicio')} onBrowse={openHomeBrowse}/>} {view==='Mapa'&&<MapView plans={createdPlans} onBack={()=>setView('Inicio')} onPlan={p=>openPlan(p,'Mapa')}/>} {view==='HomeBrowse'&&<HomeBrowseView extraPlans={createdPlans} mode={homeBrowseMode} category={homeBrowseCategory} onBack={()=>setView('Inicio')} onPlan={p=>openPlan(p,'HomeBrowse')} onBrowse={openHomeBrowse}/>} {view==='Explora'&&<ExploreView onPlan={p=>openPlan(p,'Explora')} extraPlans={createdPlans} initialFilter={exploreFilter} initialCategory={exploreCategory} onChat={openContactChat}/>} {view==='Chat'&&<ChatView initialContact={chatTarget} initialPlanTarget={planChatTarget}/>} {view==='Perfil'&&<ProfileEnhancedView setView={setView}/>} {view==='Ajustes'&&<SettingsView/>}{view==='Notificaciones'&&<NotificationsView onUnreadCountChange={setUnreadNotifications} onOpenPlanChat={id=>openChat(undefined,id)}/>} {view==='Crear'&&<CreatePlanView setView={n=>{if(n==='Explora')openHomeBrowse('all');else setView(n)}} onCreate={addCreatedPlan}/>} {view==='Calendario'&&<CalendarView setView={setView}/>} {view==='Plan'&&selected&&<PlanDetail plan={selected} onClose={closePlan} onOpenChat={openChat} standalone/>}</div></main><BottomNav view={view} activeView={navigationView} setView={setView}/></div>;
}
