import type { Community, Plan, Profile } from "./types";

const DEMO_STORAGE_KEY = "conecta-demo-mode";
export const DEMO_MODE_DEFAULT = true;
export const DEMO_ID_PREFIX = "demo-";

const now = Date.now();
const isoIn = (hours: number) => new Date(now + hours * 60 * 60 * 1000).toISOString();

export const demoProfiles: Profile[] = [
  {
    id: "demo-profile-laura",
    username: "laura.run",
    display_name: "Laura",
    bio: "Running suave, brunch y planes al aire libre.",
    birth_date: "1997-06-18",
    city: "Tarragona",
    country: "España",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=86",
    cover_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=82",
    interests: ["running", "café", "playa"],
    latitude: 41.1189,
    longitude: 1.2445,
    profile_visibility: "public",
    show_location: true,
    show_age: true,
    show_online: true,
    allow_messages: "everyone",
    online: true,
    last_seen: null,
    availability: {},
    languages: ["Español", "Català"],
    social_goals: ["amistad", "deporte"],
    activity_levels: { running: "intermediate" },
    max_distance_km: 30,
    preferred_group_size: "small",
    preferred_atmospheres: ["social", "calm"],
    budget_max_cents: 3000,
    onboarding_completed: true,
    identity_status: "verified",
  },
  {
    id: "demo-profile-marc",
    username: "marc.foodie",
    display_name: "Marc",
    bio: "Descubriendo restaurantes, fotografía y escapadas de fin de semana.",
    birth_date: "1994-11-02",
    city: "Reus",
    country: "España",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=86",
    cover_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=82",
    interests: ["gastronomía", "foto", "viajes"],
    latitude: 41.1549,
    longitude: 1.1087,
    profile_visibility: "public",
    show_location: true,
    show_age: true,
    show_online: true,
    allow_messages: "everyone",
    online: false,
    last_seen: isoIn(-2),
    availability: {},
    languages: ["Español", "English"],
    social_goals: ["amistad", "planes"],
    activity_levels: {},
    max_distance_km: 40,
    preferred_group_size: "medium",
    preferred_atmospheres: ["social"],
    budget_max_cents: 5000,
    onboarding_completed: true,
    identity_status: "verified",
  },
  {
    id: "demo-profile-nuria",
    username: "nuria.padeln",
    display_name: "Núria",
    bio: "Pádel, gimnasio y gente con ganas de moverse.",
    birth_date: "1998-03-12",
    city: "Salou",
    country: "España",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=86",
    cover_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=82",
    interests: ["pádel", "gimnasio", "playa"],
    latitude: 41.0766,
    longitude: 1.1444,
    profile_visibility: "public",
    show_location: true,
    show_age: true,
    show_online: true,
    allow_messages: "connections",
    online: true,
    last_seen: null,
    availability: {},
    languages: ["Català", "Español"],
    social_goals: ["deporte", "amistad"],
    activity_levels: { padel: "intermediate" },
    max_distance_km: 25,
    preferred_group_size: "small",
    preferred_atmospheres: ["social", "intense"],
    budget_max_cents: 2500,
    onboarding_completed: true,
    identity_status: "verified",
  },
  {
    id: "demo-profile-david",
    username: "david.outdoor",
    display_name: "David",
    bio: "Senderismo, bici y rutas con buenas vistas.",
    birth_date: "1992-09-07",
    city: "Cambrils",
    country: "España",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=86",
    cover_url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=82",
    interests: ["senderismo", "ciclismo", "naturaleza"],
    latitude: 41.067,
    longitude: 1.057,
    profile_visibility: "public",
    show_location: true,
    show_age: true,
    show_online: true,
    allow_messages: "everyone",
    online: false,
    last_seen: isoIn(-5),
    availability: {},
    languages: ["Español"],
    social_goals: ["amistad", "aventura"],
    activity_levels: { cycling: "advanced" },
    max_distance_km: 50,
    preferred_group_size: "medium",
    preferred_atmospheres: ["calm", "social"],
    budget_max_cents: 4000,
    onboarding_completed: true,
    identity_status: "verified",
  },
];

export const demoPlans: Plan[] = [
  {
    id: "demo-plan-running-serralada",
    creator_id: "demo-profile-laura",
    title: "Running suave al atardecer",
    description: "5 km a ritmo cómodo y estiramientos al terminar. Perfecto para conocer gente sin presión.",
    category: "Running",
    location_name: "Passeig Marítim, Tarragona",
    latitude: 41.116,
    longitude: 1.258,
    starts_at: isoIn(7),
    ends_at: isoIn(8.5),
    expires_at: isoIn(9),
    max_people: 8,
    min_people: 2,
    image_url: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "beginner",
    atmosphere: "social",
    cost_cents: 0,
    currency: "EUR",
    approximate_age_min: 22,
    approximate_age_max: 40,
    approval_mode: "automatic",
    requirements: ["Zapatillas cómodas", "Agua"],
    logistics: {},
    sport_details: { distance_km: 5 },
    is_spontaneous: false,
    recurrence_rule: null,
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-18),
    newcomer_friendly: true,
  },
  {
    id: "demo-plan-brunch-reus",
    creator_id: "demo-profile-marc",
    title: "Brunch y café de especialidad",
    description: "Mesa tranquila para probar un sitio nuevo y charlar sin prisas.",
    category: "Café",
    location_name: "Centre, Reus",
    latitude: 41.155,
    longitude: 1.107,
    starts_at: isoIn(20),
    ends_at: isoIn(22),
    expires_at: isoIn(22),
    max_people: 6,
    min_people: 2,
    image_url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "all",
    atmosphere: "calm",
    cost_cents: 1800,
    currency: "EUR",
    approximate_age_min: 24,
    approximate_age_max: 42,
    approval_mode: "automatic",
    requirements: [],
    logistics: {},
    sport_details: {},
    is_spontaneous: false,
    recurrence_rule: null,
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-14),
    newcomer_friendly: true,
  },
  {
    id: "demo-plan-padel-salou",
    creator_id: "demo-profile-nuria",
    title: "Partido de pádel nivel medio",
    description: "Partido amistoso de 90 minutos. Falta una pareja para completar pista.",
    category: "Pádel",
    location_name: "Club esportiu, Salou",
    latitude: 41.081,
    longitude: 1.148,
    starts_at: isoIn(28),
    ends_at: isoIn(29.5),
    expires_at: isoIn(30),
    max_people: 4,
    min_people: 4,
    image_url: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "intermediate",
    atmosphere: "intense",
    cost_cents: 900,
    currency: "EUR",
    approximate_age_min: 20,
    approximate_age_max: 45,
    approval_mode: "manual",
    requirements: ["Pala propia"],
    logistics: {},
    sport_details: { duration_minutes: 90 },
    is_spontaneous: false,
    recurrence_rule: null,
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-10),
  },
  {
    id: "demo-plan-senderismo-prades",
    creator_id: "demo-profile-david",
    title: "Ruta de senderismo por Prades",
    description: "Ruta de mañana con parada para desayunar y fotos. Nivel medio, sin prisas.",
    category: "Senderismo",
    location_name: "Prades, Tarragona",
    latitude: 41.309,
    longitude: 0.988,
    starts_at: isoIn(52),
    ends_at: isoIn(58),
    expires_at: isoIn(59),
    max_people: 10,
    min_people: 3,
    image_url: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "intermediate",
    atmosphere: "social",
    cost_cents: 0,
    currency: "EUR",
    approximate_age_min: 22,
    approximate_age_max: 50,
    approval_mode: "automatic",
    requirements: ["Calzado de montaña", "Agua", "Algo de comida"],
    logistics: { transport: "coches compartidos" },
    sport_details: { distance_km: 11 },
    is_spontaneous: false,
    recurrence_rule: null,
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-8),
    newcomer_friendly: true,
  },
  {
    id: "demo-plan-cena-tapas",
    creator_id: "demo-profile-marc",
    title: "Cena de tapas y gente nueva",
    description: "Grupo pequeño para cenar, compartir platos y conocer gente de la zona.",
    category: "Comida",
    location_name: "Part Alta, Tarragona",
    latitude: 41.1198,
    longitude: 1.2586,
    starts_at: isoIn(32),
    ends_at: isoIn(35),
    expires_at: isoIn(35),
    max_people: 7,
    min_people: 3,
    image_url: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "all",
    atmosphere: "social",
    cost_cents: 2800,
    currency: "EUR",
    approximate_age_min: 25,
    approximate_age_max: 45,
    approval_mode: "automatic",
    requirements: [],
    logistics: {},
    sport_details: {},
    is_spontaneous: false,
    recurrence_rule: null,
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-6),
    newcomer_friendly: true,
  },
  {
    id: "demo-plan-gym-functional",
    creator_id: "demo-profile-nuria",
    title: "Entreno funcional en grupo",
    description: "Sesión de fuerza y movilidad con nivel adaptable y café después para quien se anime.",
    category: "Gimnasio",
    location_name: "La Pineda, Vila-seca",
    latitude: 41.076,
    longitude: 1.181,
    starts_at: isoIn(15),
    ends_at: isoIn(16.25),
    expires_at: isoIn(17),
    max_people: 8,
    min_people: 2,
    image_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    level: "all",
    atmosphere: "intense",
    cost_cents: 500,
    currency: "EUR",
    approximate_age_min: 20,
    approximate_age_max: 45,
    approval_mode: "automatic",
    requirements: ["Toalla", "Agua"],
    logistics: {},
    sport_details: {},
    is_spontaneous: false,
    recurrence_rule: "weekly",
    meeting_safety: "public_place",
    status: "published",
    created_at: isoIn(-5),
  },
];

export const demoCommunities: Community[] = [
  {
    id: "demo-community-running",
    owner_id: "demo-profile-laura",
    name: "Running Tarragona Social",
    description: "Quedadas semanales, ritmos variados y cero presión.",
    image_url: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    category: "Running",
    location_name: "Tarragona",
    member_limit: 80,
    recurrence_rule: "weekly",
    rules: ["Buen ambiente", "Respeto a todos los ritmos"],
    auto_approve: true,
    organizer_tier: "verified",
    created_at: isoIn(-500),
  },
  {
    id: "demo-community-food",
    owner_id: "demo-profile-marc",
    name: "Foodies Camp de Tarragona",
    description: "Restaurantes nuevos, brunch, tapas y gastronomía local.",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    category: "Gastronomía",
    location_name: "Tarragona y Reus",
    member_limit: 120,
    recurrence_rule: "monthly",
    rules: ["Reservas responsables", "Avisar si cancelas"],
    auto_approve: true,
    organizer_tier: "verified",
    created_at: isoIn(-430),
  },
  {
    id: "demo-community-padel",
    owner_id: "demo-profile-nuria",
    name: "Pádel Costa Daurada",
    description: "Partidos por niveles y parejas rotativas durante toda la semana.",
    image_url: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    category: "Pádel",
    location_name: "Salou y Vila-seca",
    member_limit: 100,
    recurrence_rule: "weekly",
    rules: ["Indicar nivel real", "Puntualidad"],
    auto_approve: true,
    organizer_tier: "verified",
    created_at: isoIn(-380),
  },
  {
    id: "demo-community-outdoor",
    owner_id: "demo-profile-david",
    name: "Rutas y escapadas Tarragona",
    description: "Senderismo, bici y escapadas de un día por Cataluña.",
    image_url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=86",
    visibility: "public",
    category: "Aventura",
    location_name: "Provincia de Tarragona",
    member_limit: 150,
    recurrence_rule: "monthly",
    rules: ["Seguridad primero", "No dejar a nadie atrás"],
    auto_approve: false,
    organizer_tier: "verified",
    created_at: isoIn(-340),
  },
];

export function isDemoEntityId(id: string | null | undefined) {
  return Boolean(id?.startsWith(DEMO_ID_PREFIX));
}

export function isDemoModeEnabled() {
  if (typeof window === "undefined") return DEMO_MODE_DEFAULT;
  const stored = window.localStorage.getItem(DEMO_STORAGE_KEY);
  return stored == null ? DEMO_MODE_DEFAULT : stored === "1";
}

export function setDemoModeEnabled(enabled: boolean) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(DEMO_STORAGE_KEY, enabled ? "1" : "0");
}

function mergeUnique<T>(real: T[], demo: T[], key: (item: T) => string) {
  const seen = new Set(real.map(key));
  return [...real, ...demo.filter((item) => !seen.has(key(item)))];
}

export function mergeDemoPlans(real: Plan[], enabled: boolean) {
  return enabled ? mergeUnique(real, demoPlans, (plan) => `${plan.id}|${plan.title.toLowerCase()}`) : real;
}

export function mergeDemoProfiles(real: Profile[], enabled: boolean) {
  return enabled ? mergeUnique(real, demoProfiles, (profile) => `${profile.id}|${profile.username ?? profile.display_name ?? ""}`.toLowerCase()) : real;
}

export function mergeDemoCommunities(real: Community[], enabled: boolean) {
  return enabled ? mergeUnique(real, demoCommunities, (community) => `${community.id}|${community.name.toLowerCase()}`) : real;
}
