import type { Plan, Profile } from "./types";

const dateFormatter = new Intl.DateTimeFormat("es-ES", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
export function formatPlanDate(value: string | null) { if (!value) return "Fecha por confirmar"; return dateFormatter.format(new Date(value)).replace(",", " ·"); }
export function formatMoney(cents: number, currency = "EUR") { if (!cents) return "Gratis"; return new Intl.NumberFormat("es-ES", { style: "currency", currency, maximumFractionDigits: 2 }).format(cents / 100); }
export function formatLevel(level: Plan["level"]) { return { all: "Todos los niveles", beginner: "Principiante", intermediate: "Intermedio", advanced: "Avanzado", competition: "Competición" }[level]; }
export function formatAtmosphere(atmosphere: Plan["atmosphere"]) { return { calm: "Tranquilo", social: "Social", intense: "Intenso", party: "Fiesta" }[atmosphere]; }
export function yearsOld(birthDate: string | null) { if (!birthDate) return null; const birth = new Date(birthDate); const now = new Date(); let years = now.getFullYear() - birth.getFullYear(); const beforeBirthday = now.getMonth() < birth.getMonth() || (now.getMonth() === birth.getMonth() && now.getDate() < birth.getDate()); if (beforeBirthday) years -= 1; return years; }
function radians(value: number) { return (value * Math.PI) / 180; }
export function distanceKm(lat1: number | null, lon1: number | null, lat2: number | null, lon2: number | null) { if (lat1 == null || lon1 == null || lat2 == null || lon2 == null) return null; const earthRadius = 6371; const dLat = radians(lat2 - lat1); const dLon = radians(lon2 - lon1); const a = Math.sin(dLat / 2) ** 2 + Math.cos(radians(lat1)) * Math.cos(radians(lat2)) * Math.sin(dLon / 2) ** 2; return earthRadius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
export function planCompatibility(plan: Plan, profile: Profile | null) { if (!profile) return 70; let score = 55; if (profile.interests.some((interest) => interest.toLowerCase() === plan.category?.toLowerCase())) score += 20; const activityLevel = plan.category ? profile.activity_levels[plan.category] : null; if (plan.level === "all" || activityLevel === plan.level) score += 10; if (profile.budget_max_cents == null || plan.cost_cents <= profile.budget_max_cents) score += 5; if (profile.preferred_atmospheres.includes(plan.atmosphere)) score += 5; const distance = distanceKm(profile.latitude, profile.longitude, plan.latitude, plan.longitude); if (distance != null && distance <= Number(profile.max_distance_km || 15)) score += 5; return Math.min(score, 99); }
export function personCompatibility(person: Profile, profile: Profile | null) { if (!profile) return 75; const shared = person.interests.filter((interest) => profile.interests.includes(interest)).length; const languageMatch = person.languages.some((language) => profile.languages.includes(language)); const goalMatch = person.social_goals.some((goal) => profile.social_goals.includes(goal)); const sameCity = Boolean(person.city && profile.city && person.city === profile.city); return Math.min(62 + shared * 7 + (languageMatch ? 6 : 0) + (goalMatch ? 8 : 0) + (sameCity ? 5 : 0), 99); }
export function mapEmbedUrl(plan?: Plan | null) { const lat = plan?.latitude ?? 41.1189; const lon = plan?.longitude ?? 1.2445; const offset = plan ? 0.025 : 0.09; const bbox = `${lon - offset},${lat - offset},${lon + offset},${lat + offset}`; const marker = plan?.latitude != null && plan?.longitude != null ? `&marker=${lat},${lon}` : ""; return `https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik${marker}`; }
function icsDate(value: string | null) { return value ? new Date(value).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "") : ""; }
export function downloadPlanCalendar(plan: Plan) { if (!plan.starts_at) return false; const start = icsDate(plan.starts_at); const end = icsDate(plan.ends_at ?? new Date(new Date(plan.starts_at).getTime() + 90 * 60_000).toISOString()); const safe = (value: string) => value.replace(/([,;])/g, "\\$1").replace(/\n/g, "\\n"); const content = ["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//CONECTA//Plan social//ES","BEGIN:VEVENT",`UID:${plan.id}@conecta`,`DTSTAMP:${icsDate(new Date().toISOString())}`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${safe(plan.title)}`,`LOCATION:${safe(plan.location_name ?? "Punto de encuentro por confirmar")}`,`DESCRIPTION:${safe(plan.description ?? "Plan organizado en CONECTA")}`,"END:VEVENT","END:VCALENDAR"].join("\r\n"); const blob = new Blob([content], { type: "text/calendar;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${plan.title.toLowerCase().replace(/[^a-z0-9]+/gi, "-")}.ics`; link.click(); URL.revokeObjectURL(url); return true; }
